apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
  namespace: finops-bank
  labels:
    app: audit-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-service
  template:
    metadata:
      labels:
        app: audit-service
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: audit-service
        image: ghcr.io/ivanoliveraprofesional-code/audit-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_CLOUD_AWS_ENDPOINT
          value: "http://localstack:4566"
        - name: SPRING_CLOUD_AWS_REGION_STATIC
          value: "us-east-1"
        - name: SPRING_CLOUD_AWS_CREDENTIALS_ACCESS_KEY
          value: "test"
        - name: SPRING_CLOUD_AWS_CREDENTIALS_SECRET_KEY
          value: "test"
        - name: APP_MESSAGING_QUEUE_NAME
          value: "finops-audit-queue"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"