apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finops-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ivanoliveraprofesional-code/finops-bank-platform.git
    targetRevision: HEAD
    path: kubernetes/platform
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: finops-bank
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finops-security
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ivanoliveraprofesional-code/finops-bank-platform.git
    targetRevision: HEAD
    path: kubernetes/security
  destination:
    server: https://kubernetes.default.svc
    namespace: finops-bank
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finops-microservices
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ivanoliveraprofesional-code/finops-bank-platform.git
    targetRevision: HEAD
    path: kubernetes/apps
    directory:
      recurse: true    # Deploys auth, core, risk, audit recursively
  destination:
    server: https://kubernetes.default.svc
    namespace: finops-bank
  syncPolicy:
    automated:
      prune: true
      selfHeal: true