version: "3.8"

services:
  postgres-dev:
    image: postgres:13-alpine
    container_name: finops-postgres-dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init-scripts/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack-dev:
    image: localstack/localstack:3.2
    container_name: finops-localstack-dev
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,sqs,secretsmanager
      - DEBUG=1
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./init-scripts/localstack:/etc/localstack/init/ready.d

volumes:
  postgres_data:
  localstack_data:
