apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-banking
  namespace: finops-bank
  labels:
    app: core-banking
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-banking
  template:
    metadata:
      labels:
        app: core-banking
        tier: backend
        security: protected 
      annotations:
        sidecar.istio.io/proxyCPU: "20m"
        sidecar.istio.io/proxyMemory: "50Mi"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: core-banking
        image: ghcr.io/ivanoliveraprofesional-code/core-banking-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: MANAGEMENT_SERVER_PORT
          value: "8082"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: finops-config
              key: SPRING_DATASOURCE_URL_CORE
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: DB_PASSWORD
        - name: GRPC_CLIENT_CREDIT_RISK_SERVICE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: finops-config
              key: GRPC_CLIENT_RISK_ADDRESS
        - name: SPRING_CLOUD_AWS_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: finops-config
              key: AWS_ENDPOINT_URL
        - name: SPRING_CLOUD_AWS_REGION_STATIC
          value: "us-east-1"
        - name: SPRING_CLOUD_AWS_CREDENTIALS_ACCESS_KEY
          value: "test"
        - name: SPRING_CLOUD_AWS_CREDENTIALS_SECRET_KEY
          value: "test"
        resources:
          requests:
            memory: "300Mi"
            cpu: "250m"
          limits:
            memory: "600Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
        - containerPort: 8082
