apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-banking
  namespace: finops-bank
  labels:
    app: core-banking
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-banking
  template:
    metadata:
      labels:
        app: core-banking
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
        traffic.sidecar.istio.io/excludeOutboundPorts: "5432"
    spec:
      containers:
      - name: core-banking
        image: ghcr.io/ivanoliveraprofesional-code/core-banking-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: finops-config
              key: SPRING_DATASOURCE_URL_CORE
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"