apiVersion: v1
kind: ConfigMap
metadata:
  name: finops-config
  namespace: finops-bank
data:
  SPRING_DATASOURCE_URL_AUTH: "jdbc:postgresql://postgres-db:5432/finops_auth"
  SPRING_DATASOURCE_URL_CORE: "jdbc:postgresql://postgres-db:5432/finops_core_banking"
  
  GRPC_CLIENT_RISK_ADDRESS: "static://credit-risk-service:9090"
  
  AWS_ENDPOINT_URL: "http://host.docker.internal:4566"
  AWS_REGION: "us-east-1"