apiVersion: v1
kind: ConfigMap
metadata:
  name: finops-config
  namespace: finops-bank
data:
  SPRING_DATASOURCE_URL_AUTH: "jdbc:postgresql://postgres-db.finops-bank.svc.cluster.local:5432/finops_auth?sslmode=disable"
  SPRING_DATASOURCE_URL_CORE: "jdbc:postgresql://postgres-db.finops-bank.svc.cluster.local:5432/finops_core_banking?sslmode=disable"
  
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  SPRING_PROFILES_ACTIVE: "default"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,prometheus"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_FINOPS: "DEBUG"