apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: finops-bank
type: Opaque
stringData:
  JWT_PRIVATE_KEY: "PLACEHOLDER"
  JWT_PUBLIC_KEY: "PLACEHOLDER"
  DB_PASSWORD: "app_password_placeholder"